---
- name: Create Instance
  hosts: all
  vars:
    kolla_config_path: /etc/kolla
    instance_name: test
    project_name: k8s
    instance_name: bastion
    image_name: jammy-server-cloudimg-amd64
    instance_key: mykey
    instance_flavor: m1.small

  environment:
        OS_CLIENT_CONFIG_FILE: "{{ kolla_config_path }}/clouds.yaml"
        OS_CLOUD: "kolla-admin"

  tasks:

    - name: Install openstack SDK
      ansible.builtin.pip:
        name: openstacksdk>=1.0.0
    - name: Check for clouds.yaml
      ansible.builtin.stat:
        path: "{{ kolla_config_path }}/clouds.yaml"
      register: clouds_yaml

    - name: Fail if clouds.yaml is missing
      ansible.builtin.fail:
        msg: "{{ kolla_config_path }}/clouds.yaml is missing. Did your deploy finish successfully?"
      when: not clouds_yaml.stat.exists

    - name:  "Create a new instance {{ instance_name }}"
      openstack.cloud.server:
        project: "{{ project_name }}"
        state: present
        name:  "{{ instance_name }}"
        image: "{{ image_name }}"
        key_name: "{{ instance_key }}"
        timeout: 200
        flavor: "{{ instance_flavor }}"
        nics:
          - net-name: demo-net
        auto_ip: false
        meta:
          hostname: "{{ instance_name }}"
          group: instance
        userdata: |
          #cloud-config
          password: ubuntu
          ssh_pwauth: True
          chpasswd: { expire: False }
          package_update: true
          package_upgrade: true
